# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates: 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      api-version-updates: 

  - package-ecosystem: "npm"
    directory: "/front-react"
    schedule:
      interval: "daily"
    versioning-strategy: increase
      front-react-version-updates:
